### ISSUE TITLE
Report (html) has a rendering issue in Firefox

### ISSUE THREAD

**Issue by jungshik** [icu-project/text-rendering-tests#4] opened 2016-10-11 20:02 UTC
At https://raw.githack.com/icu-project/text-rendering-tests/master/reports/FreeStack.html , SVG 'glyphs/images' in  'Expected' and 'Observed' lines are vertically misaligned and only partially shown. 
(observed with Firefox 49 on Ubuntu). 

This may as well be a Firefox issue and coming up with a work-around should be a very low priority. Just reporting as an FYI item.

![image](https://cloud.githubusercontent.com/assets/8578343/19286462/abe65156-8fb2-11e6-906e-5fc8c568e64e.png)

**Comment by brawer** [comment] 2016-10-24 20:22
Thanks for telling! I had reported [bug 1305078](https://bugzilla.mozilla.org/show_bug.cgi?id=1305078) which got classified as duplicate of 
[bug 265894](https://bugzilla.mozilla.org/show_bug.cgi?id=265894). So, apparently Firefox had this problem since 2004 but it’s still not fixed. :-(

**Closed by brawer** 2016-10-24 20:22 UTC
